/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.polyglot;

public final class R {
  public static final class id {
    public static final int display_view=0x7f010000;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
}