#!/data/data/com.termux/files/usr/bin/bash
set -e

echo ">> Configuring mkapk build system..."

mkdir -p /data/data/com.termux/files/home/android-sdk/Sdk/cmdline-tools

# Download and extract the archive package
echo ">> Downloading Android SDK command-line tools."
wget -O /data/data/com.termux/files/home/commandlinetools-linux-14742923_latest.zip https://dl.google.com/android/repository/commandlinetools-linux-14742923_latest.zip

echo ">> Extracting  command-line tools."
unzip /data/data/com.termux/files/home/commandlinetools-linux-14742923_latest.zip -d /data/data/com.termux/files/home/android-sdk/Sdk/cmdline-tools/

# Rearrange the root folder so it sits inside 'latest'
echo ">> Setting up Android SDK"
cd /data/data/com.termux/files/home/android-sdk/Sdk/cmdline-tools/
mv cmdline-tools latest
chmod +x /data/data/com.termux/files/home/android-sdk/Sdk/cmdline-tools/latest/bin/*
echo "export ANDROID_HOME=/data/data/com.termux/files/home/android-sdk/Sdk" >> /data/data/com.termux/files/usr/etc/bash.bashrc
echo "export PATH=$PATH:/data/data/com.termux/files/home/android-sdk/Sdk/cmdline-tools/latest/bin" >> /data/data/com.termux/files/usr/etc/bash.bashrc
source /data/data/com.termux/files/usr/etc/bash.bashrc

echo "Downloading Android SDK platform 13"
/data/data/com.termux/files/home/android-sdk/Sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
cd
chmod +x $PREFIX/bin/mkapk
rm /data/data/com.termux/files/home/commandlinetools-linux-14742923_latest.zip
echo ">> Setup complete."
echo ">> Type 'mkapk' to begin."

exit 0